FROM python:3.12-slim

RUN pip3 install --upgrade pip

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY server_dynamo.py .
COPY common.py .

# Expor a porta
EXPOSE 5500

# Comando para iniciar a aplicação
CMD ["python", "server_dynamo.py"]