FROM python:3.12-slim

RUN pip3 install --upgrade pip

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY server_location.py .

EXPOSE 5500

CMD ["python", "server_location.py"]